# Players generally sit in a circle. The player designated to go first says the
# number "1", and each player thenceforth counts one number in turn. However,
# any number divisible by 'A' e.g. three is replaced by the word fizz and any
# divisible by 'B' e.g. five by the word buzz. Numbers divisible by both become
# fizz buzz. A player who hesitates or makes a mistake is either eliminated.
#
# Write a program that prints out the the pattern generated by such a scenario
# given the values of 'A'/'B' and 'N' which are read from an input text file.
# The input text file contains three space delimited numbers i.e. A, B, N. The
# program should then print out the final series of numbers using 'F' for fizz,
# 'B' for 'buzz' and 'FB' for fizz buzz.

File.open(ARGV[0]).each_line do |line|
  a, b, n = line.split.map(&:to_i)
  output = (1..n).map do |i|
    o = ''
    o << 'F' if i % a == 0
    o << 'B' if i % b == 0
    o.empty? ? i : o
  end.join(' ')
  puts output
end
